import type { Lang } from "./types"

const en = {
  nav: { work: "Projects", blog: "Blog", exp: "Experience", talk: "Let's talk", me: "Me", menu: "Menu" },
  status: "Available for technical co-founding · Madrid",
  heroTitle: "I build AI-native products with founders who move fast.",
  heroSub:
    "CEO & Co-Founder @ Collybrix. 15+ years shipping software — from frontend to VP of Engineering — now acting as temporary technical co-founder for startups going from idea to 100K users.",
  ctaPrimary: "Book a 30-min call",
  ctaSecondary: "See projects",
  collyLabel: "What is Collybrix",
  collyTitle: "We fast-track startup tech — and rewrite the standards.",
  collyBody:
    "A technical accelerator for startups across Europe and the Americas. Our senior team — backend, frontend, data & AI, UX/UI, DevOps — takes founders from concept to a robust, scalable product (Prototype → MVP → v1.0) in a few months.",
  stats: ["years shipping software", "companies founded", "users — the target for every startup we join"],
  stackLabel: "Stack",
  projectsLabel: "Selected work",
  projectsTitle: "Products I'm building",
  allProjects: "All projects",
  expLabel: "Experience & Education",
  expTitle: "Fifteen years, three continents, one obsession: shipping.",
  fullExp: "Full timeline",
  education: "Education",
  current: "Now",
  roles: "roles",
  certifications: "Certifications · Platzi",
  languages: "Languages",
  languageLevels: { es: "Native", en: "Full professional", fr: "Elementary" },
  blogLabel: "Writing",
  blogTitle: "Notes on AI, startups and engineering leadership",
  allPosts: "All posts",
  readMore: "Read",
  minRead: "min read",
  allTag: "All",
  newsLabel: "Newsletter",
  newsTitle: "One useful idea every two weeks.",
  newsBody: "On AI engineering, technical strategy for founders and what we learn at Collybrix. No noise.",
  newsPlaceholder: "you@company.com",
  newsCta: "Subscribe",
  newsDone: "You're in. Check your inbox.",
  newsError: "Something went wrong. Try again.",
  talkLabel: "Let's talk",
  talkTitle: "Have an idea that needs a technical co-founder?",
  talkBody: "Tell me what you're building. I reply within 48 hours.",
  fName: "Name",
  fEmail: "Email",
  fMsg: "What are you building?",
  fSend: "Send message",
  fSending: "Sending…",
  fDone: "Thanks — talk soon.",
  fError: "Couldn't send. Email me directly.",
  footer: "Madrid, Spain",
  about: "About me",
  rights: "All rights reserved.",
  blogPageTitle: "Writing",
  blogPageSub: "Long-form notes on building AI-native products, leading engineering teams and accelerating startups.",
  projPageTitle: "Projects",
  projPageSub: "Products built at Collybrix and beyond — each one a real bet on a real problem.",
  back: "Back home",
  backToBlog: "All posts",
  onThisPage: "On this page",
  notTranslated: "This post isn't translated yet — showing the Spanish version.",
  autoTranslated: "Translated automatically from Spanish.",
  client: "Client",
  role: "Role",
  stack: "Stack",
  year: "Year",
  meLabel: "About me",
  meRole: "CEO & Co-Founder @ Collybrix · Madrid, ES",
  bioPlaceholder: "[ PERSONAL BIO — 3-4 lines in first person: where I'm from, what drives me outside work, why I do this. ]",
  storyLabel: "The story",
  storyTitle: "From frontend to VP of Engineering to technical co-founder.",
  facts: ["years in software", "companies founded", "roles across 3 continents", "developers taught"],
}

export type Copy = typeof en

const es: Copy = {
  nav: { work: "Proyectos", blog: "Blog", exp: "Experiencia", talk: "Hablemos", me: "Yo", menu: "Menú" },
  status: "Disponible como co-founder técnico · Madrid",
  heroTitle: "Construyo productos AI-native con founders que van rápido.",
  heroSub:
    "CEO & Co-Founder @ Collybrix. Más de 15 años haciendo software — de frontend a VP de Ingeniería — hoy como co-founder técnico temporal para startups que van de la idea a 100K usuarios.",
  ctaPrimary: "Agendar 30 min",
  ctaSecondary: "Ver proyectos",
  collyLabel: "Qué es Collybrix",
  collyTitle: "Aceleramos la tecnología de startups — y reescribimos el estándar.",
  collyBody:
    "Una aceleradora técnica para startups de Europa y América. Nuestro equipo senior — backend, frontend, data & AI, UX/UI, DevOps — lleva a los founders de la idea a un producto robusto y escalable (Prototipo → MVP → v1.0) en pocos meses.",
  stats: ["años construyendo software", "empresas fundadas", "usuarios: la meta de cada startup que acompañamos"],
  stackLabel: "Stack",
  projectsLabel: "Trabajo seleccionado",
  projectsTitle: "Productos que estoy construyendo",
  allProjects: "Todos los proyectos",
  expLabel: "Experiencia y Educación",
  expTitle: "Quince años, tres continentes, una obsesión: lanzar.",
  fullExp: "Timeline completo",
  education: "Educación",
  current: "Ahora",
  roles: "roles",
  certifications: "Certificaciones · Platzi",
  languages: "Idiomas",
  languageLevels: { es: "Nativo", en: "Profesional", fr: "Básico" },
  blogLabel: "Escritos",
  blogTitle: "Notas sobre IA, startups y liderazgo técnico",
  allPosts: "Todos los posts",
  readMore: "Leer",
  minRead: "min",
  allTag: "Todos",
  newsLabel: "Newsletter",
  newsTitle: "Una idea útil cada dos semanas.",
  newsBody: "Sobre ingeniería con IA, estrategia técnica para founders y lo que aprendemos en Collybrix. Sin ruido.",
  newsPlaceholder: "tu@empresa.com",
  newsCta: "Suscribirme",
  newsDone: "Listo. Revisá tu inbox.",
  newsError: "Algo salió mal. Probá de nuevo.",
  talkLabel: "Hablemos",
  talkTitle: "¿Tenés una idea que necesita un co-founder técnico?",
  talkBody: "Contame qué estás construyendo. Respondo en 48 horas.",
  fName: "Nombre",
  fEmail: "Email",
  fMsg: "¿Qué estás construyendo?",
  fSend: "Enviar mensaje",
  fSending: "Enviando…",
  fDone: "Gracias — hablamos pronto.",
  fError: "No se pudo enviar. Escribime directo.",
  footer: "Madrid, España",
  about: "Sobre mí",
  rights: "Todos los derechos reservados.",
  blogPageTitle: "Escritos",
  blogPageSub: "Notas largas sobre construir productos AI-native, liderar equipos de ingeniería y acelerar startups.",
  projPageTitle: "Proyectos",
  projPageSub: "Productos construidos en Collybrix y más allá — cada uno una apuesta real sobre un problema real.",
  back: "Volver al inicio",
  backToBlog: "Todos los posts",
  onThisPage: "En esta página",
  notTranslated: "Este post aún no está traducido — se muestra la versión en inglés.",
  autoTranslated: "Traducido automáticamente del inglés.",
  client: "Cliente",
  role: "Rol",
  stack: "Stack",
  year: "Año",
  meLabel: "Sobre mí",
  meRole: "CEO & Co-Founder @ Collybrix · Madrid, ES",
  bioPlaceholder: "[ BIO PERSONAL — 3-4 líneas en primera persona: de dónde soy, qué me mueve fuera del trabajo, por qué hago lo que hago. ]",
  storyLabel: "La historia",
  storyTitle: "De frontend a VP de Ingeniería a co-founder técnico.",
  facts: ["años en software", "empresas fundadas", "roles en 3 continentes", "developers formados"],
}

export const copy: Record<Lang, Copy> = { en, es }
