import type { ExperienceFull, ExperienceShort } from "./types"

export const experienceShort: ExperienceShort[] = [
  { company: "Collybrix", role: "CEO & Co-Founder", from: "2025", to: "", loc: "Madrid" },
  { company: "AKAIO by Kyra Group", role: "VP of Engineering", from: "2024", to: "2025", loc: "Madrid" },
  { company: "Between Technology", role: "Senior Fullstack Developer", from: "2023", to: "2024", loc: "Spain" },
  { company: "Sistemas Genómicos · SYNLAB", role: "Sr Fullstack Engineer", from: "2023", to: "2023", loc: "Valencia" },
  { company: "EvoSecurity", role: "Sr. Frontend Engineer", from: "2021", to: "2023", loc: "Madrid" },
  { company: "iDocket", role: "Auth0 Engineer", from: "2022", to: "2023", loc: "Texas, US" },
  { company: "Social Native", role: "Frontend Engineer", from: "2019", to: "2022", loc: "Córdoba, AR" },
  { company: "Coderhouse", role: "ReactJS Course Teacher", from: "2020", to: "2022", loc: "Argentina" },
  { company: "Globant", role: "WebUI Developer · Disney Parks", from: "2018", to: "2019", loc: "Córdoba, AR" },
  { company: "Orange Tools", role: "Founder", from: "2011", to: "2019", loc: "Argentina" },
]

export const experienceFull: ExperienceFull[] = [
  { company: "Collybrix", role: "CEO & Co-Founder", period: "Jun 2025 — Present", location: "Madrid, Spain", current: true, description: ["Growing Collybrix, redefining startup technical acceleration.", "Guiding tech founders from concept to scalable product, leveraging 15+ years of software engineering expertise.", "Fostering authentic partnerships and continuous innovation, aligning resources with startup needs for rapid market entry."], skills: ["Technical acceleration", "AI-assisted development", "Leadership"] },
  { company: "AKAIO by Kyra Group", role: "Vice President of Engineering", period: "Nov 2024 — Sep 2025", location: "Madrid, Spain", description: ["Led end-to-end technical strategy and execution for an AI-native innovation platform.", "Launched AKAIO v1.0 — Gen AI, multi-agent systems and semantic search to simulate future scenarios.", "Directed a multi-disciplinary team: AI agents infrastructure with KrakenD, Milvus, MongoDB and a Next.js SSR frontend.", "Delivered customizable dashboards, AI-driven reporting and ecosystem mapping for innovation teams."], skills: ["Product Scaling", "AI Platforms", "Gen AI", "Multi-Agent Systems", "MongoDB", "Milvus", "KrakenD", "Next.js", "Python"] },
  { company: "AKAIO by Kyra Group", role: "Head of Development", period: "Jun 2024 — Nov 2024", location: "Madrid, Spain", description: ["Led the launch of the AKAIO MVP, validating AI agents and neural networks for innovation teams.", "Directed architecture of a cloud-native SaaS platform for innovation ecosystems.", "Introduced a rapid prototyping framework and CI/CD practices; built the core development team."], skills: ["MVP Launch", "Product Discovery", "AI Agent Design", "Cloud Architecture", "Next.js"] },
  { company: "AKAIO by Kyra Group", role: "Technical Lead", period: "Feb 2024 — Nov 2024", location: "Madrid, Spain", description: ["Led frontend and infrastructure of the early AKAIO platform, from proof-of-concept to MVP.", "Built the first AI-driven frontend with React, Astro and Next.js; defined AWS deployment strategy."], skills: ["AI Architecture", "Frontend Engineering", "AWS", "React", "Astro", "Python"] },
  { company: "Between Technology", role: "Senior Fullstack Developer", period: "May 2023 — Feb 2024", location: "Spain", description: ["Led the frontend team on an integral platform for electric assets management and data visualization (Circutor).", "Shipped a new workspaces product: support chat, analytics, alerts and events for device networks.", "Built a cross-company Design System package published to npm via GitLab CI/CD."], skills: ["Microservices", "Golang", "AWS", "GitLab CI/CD", "Next.js", "Angular", "Turborepo", "Storybook"] },
  { company: "Sistemas Genómicos · SYNLAB", role: "Sr Fullstack Engineer", period: "Apr 2023 — Oct 2023", location: "Valencia, Spain", description: ["Clean-architecture React + Node.js app on Kubernetes microservices for genomic studies.", "Analysis reports and document administration for efficient data management."], skills: ["React", "Node.js", "Kubernetes", "Clean Architecture"] },
  { company: "EvoSecurity", role: "Sr. Frontend Engineer", period: "Oct 2021 — Apr 2023", location: "Madrid, Spain", description: ["Multiple ReactJS projects in a fast-paced security startup, on AWS and Java microservices.", "Scrum and Kanban delivery."], skills: ["React", "AWS", "Java", "Microservices"] },
  { company: "iDocket", role: "Auth0 Engineer", period: "Feb 2022 — Feb 2023", location: "Texas, US", description: ["Configured and supported Auth0 solutions; implemented SSO for the Justice Department of Texas."], skills: ["Auth0", "SSO", "Security"] },
  { company: "Social Native", role: "Frontend → Fullstack Engineer", period: "Jun 2019 — Aug 2022", location: "Córdoba, Argentina", description: ["Frontend the first year, fullstack (PHP and Node.js) the last.", "Migration and maintenance of an internal Chrome Extension on AngularJS and Node.js."], skills: ["AngularJS", "React", "PHP Symfony", "Express", "AWS S3", "OpenShift"] },
  { company: "Coderhouse", role: "ReactJS Course Teacher", period: "Aug 2020 — Apr 2022", location: "Argentina", description: ["Taught ReactJS at a leading Latin American online tech school: component architecture, hooks, state, APIs.", "Code reviews, project guidance and career advice for students launching careers in tech."], skills: ["React", "Teaching", "Mentoring"] },
  { company: "MarketerHire", role: "Senior Frontend Developer", period: "Jun 2021 — Oct 2021", location: "United States", description: ["VueJS apps for a marketing talent marketplace; integrations with Make, HubSpot, Airtable, Salesforce and Crunchbase."], skills: ["Vue.js", "Integromat", "HubSpot", "Airtable", "Salesforce"] },
  { company: "WRS Health", role: "Senior Frontend Developer", period: "Mar 2021 — Jun 2021", location: "United States", description: ["Responsive ReactJS interfaces for a medical management platform, compliant with healthcare standards."], skills: ["React", "Healthcare"] },
  { company: "NaN", role: "Frontend Engineer", period: "Nov 2020 — Mar 2021", location: "Córdoba, Argentina", description: ["Uber-like transport application for trucks."], skills: ["React", "Redux", "GraphQL", "AWS Amplify", "Docker", "Tailwind"] },
  { company: "Globant", role: "WebUI Developer", period: "Jun 2018 — Jun 2019", location: "Córdoba, Argentina", description: ["Developed and maintained the Disney Parks Tickets web platform.", "Migrated Parks Tickets from PHP to a full JavaScript solution with WebComponents (Polymer)."], skills: ["React", "AngularJS", "WebComponents", "Polymer", "SCRUM"] },
  { company: "Orange Tools", role: "Founder", period: "Sep 2011 — Jun 2019", location: "Argentina", description: ["Founded and led a web development agency for 8 years — discovery, design, deployment and maintenance for local and regional clients."], skills: ["React", "AngularJS", "Express", "PHP", "WordPress", "Strapi", "Firebase", "Figma"] },
  { company: "OneClick · Apple Premier Partner", role: "Apple Certified Technician", period: "Nov 2015 — Jun 2018", location: "Córdoba, Argentina", description: ["Store Service Manager overseeing diagnostics, repairs, support and QA for Apple devices; led a team of technicians."], skills: [] },
  { company: "Ministerio de Educación Argentina", role: "Math, Tech & Physics Teacher", period: "Jan 2011 — Jun 2015", location: "Argentina", description: ["High school teacher."], skills: [] },
  { company: "Intercity SRL", role: "Technical Office", period: "Mar 2010 — Sep 2013", location: "Río Cuarto, Argentina", description: ["Tech office for an ISP provider."], skills: [] },
]
